class Autogenerated {
  int? count;
  String? next;
  Null? previous;
  List<Results>? results;

  Autogenerated({this.count, this.next, this.previous, this.results});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    count = json['count'];
    next = json['next'];
    previous = json['previous'];
    if (json['results'] != null) {
      results = <Results>[];
      json['results'].forEach((v) {
        results!.add(new Results.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['count'] = this.count;
    data['next'] = this.next;
    data['previous'] = this.previous;
    if (this.results != null) {
      data['results'] = this.results!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Results {
  int? id;
  String? order;
  String? name;
  String? notes;
  bool? active;
  List<AuxColab>? auxColab;

  Results(
      {this.id, this.order, this.name, this.notes, this.active, this.auxColab});

  Results.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    order = json['order'];
    name = json['Name'];
    notes = json['Notes'];
    active = json['Active'];
    if (json['aux.colab'] != null) {
      auxColab = <AuxColab>[];
      json['aux.colab'].forEach((v) {
        auxColab!.add(AuxColab.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['order'] = this.order;
    data['Name'] = this.name;
    data['Notes'] = this.notes;
    data['Active'] = this.active;
    if (this.auxColab != null) {
      data['aux.colab'] = this.auxColab!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class AuxColab {
  int? id;
  String? value;

  AuxColab({this.id, this.value});

  AuxColab.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['value'] = this.value;
    return data;
  }
}
